### ISSUE TITLE
ZipBomb warning from antivirus

### ISSUE THREAD

**Issue by aequi42** [inspiredware/napi-build-utils#4]
Hello,
We noticed a problem with your package on NPM.
There is another tarball `napi-build-utils-1.0.0.tgz` inside the package contents. This tarball also contains a `napi-build-utils-1.0.0.tgz` and so on. 
This goes five layers deep and is therefore detected as a zip bomb by our virus protection.

Looking through your code I could not find any reason why the inner tarball is needed. 

Am I missing something? 
Could it be that something went wrong during packaging?

Maybe it's enough to add the following to the `.npmignore`

```gitignore
# Output of 'npm pack'
*.tgz
```

**Comment by aequi42** [comment]
Thanks for your quick response!

Unfortunately, I cannot tell you exactly which virus protection we use.
I think it's a "Sophos UTM" firewall on the company network (my machine didn't complain about your package)

**Comment by jschlight** [comment]
I'll take a look at Sophos UTM. I'm closing this issue. Please reopen if the issue persists.
